### ISSUE TITLE
AI is replacing ui/form.ts incorrectly

### ISSUE THREAD

**Issue by elie222** [alephmatic/nextjs-ai#19]
Prompt:

```sh
bun run index.ts gen "add a form that creates a blog post"
```

Getting this output:

```sh
ℹ Updating existing file                                          
✔ Calling OpenAI
✔ File created at ../examples/next/components/ui/form.tsx  
```

`components/ui` folder shouldn't be updated. This is the folder where shadcn components were added. Correct output would be `components/BlogPost.tsx` or similar.

**Comment by agamm** [comment]
I think this is what I told you yesterday, try to fiddle with the knowledge?

**Comment by agamm** [comment]
Double check if this is still an issue.

**Comment by agamm** [comment]
Closing until we see this happening again - many changes already since then.
