### ISSUE TITLE
Move to a separate repo

### ISSUE THREAD

**Issue by agamm** [alephmatic/nextjs-ai#47]
I think that we need to move this project to a new repo so:
1. We could add a normal folder structure (not having to `../` for the example).
2. Call it with a more generic name like `a0` or `aleph0`.
3. Add it to an npm repository so when we publish it will send it there too.

Things to consider:
1. `a0` already exists in npm but I think we can ask them to take it as it's a very old unmaintained project.
2. I would create a second repo for a next js example using aleph0 (like our current example is) so it's easy to play with it without having to wait to bootstrap the nextjs files.

**Comment by agamm** [comment]
@elie222 What do you think?

**Comment by agamm** [comment]
Moving here:
https://github.com/alephmatic/aleph0

**Comment by elie222** [comment]
Don't separate till we need to. And that may never happen. Same way as Next.js repo includes examples.
