### ISSUE TITLE
Don't ask AI to respond with the exact same content we pass it

### ISSUE THREAD

**Issue by elie222** [alephmatic/nextjs-ai#7]
The AI has been returning the wrong info.

eg. creates a file with the name `forms.ts` or `form.js` instead of `form.ts`.
No need for it to return information we already have.

A way to mitigate is to ask it to return the name or index of the item. Or to use function calling.
If we know the valid results already no reason to allow the AI to hallucinate and do extra work.

**Comment by agamm** [comment]
This may have been resolved already.

**Comment by elie222** [comment]
Closing for now. Something to bear in mind for the future too.
