### ISSUE TITLE
Get AI to generate a more complete instructions for us

### ISSUE THREAD

**Issue by elie222** [alephmatic/nextjs-ai#9]
eg. user writes:
"create a form to post a blog"
and the AI responds with:
"Implement a HTML form with input fields for title, content, and tags to facilitate the posting of a new blog article; integrate the form with the backend API to save the data."

Example prompts:
Simple description: https://chat.openai.com/share/597dc52e-97d9-4af1-a6a1-861b38675a16
Complex description: https://chat.openai.com/share/e87079fc-8036-47f5-94af-07e8bf76576d

See how openv0 does it here with a function call:
https://github.com/raidendotai/openv0/blob/main/openv0_server/modules/multipass/design_task.js#L28-L48
https://github.com/raidendotai/openv0/blob/main/openv0_server/modules/multipass/design_task.js#L81-L91

Note how this combines what could be multiple queries into one query because it returns a JSON object (uses a function call that receives JSON as args).

We can also experiment with just adding more and more queries to keep each query as simple and focused as possible.

**Comment by agamm** [comment]
Is this message relevant to this?
> Return json object with the following:
> Instructions: “create a new form to create blog posts…”,
> Relevant snippets: [form, api,…]

**Comment by elie222** [comment]
> Is this message relevant to this?
> 
> > Return json object with the following:
> > Instructions: “create a new form to create blog posts…”,
> > Relevant snippets: [form, api,…]

Yes

**Comment by agamm** [comment]
You completed this already, no? @elie222

**Comment by elie222** [comment]
Yes
